name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 46.202.182.199
        username: u815786501.ehtshaamrajpoot.com
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          deploy.py
          install.php
          database.sql
          update_about.sql
          website_ready.zip
          .system_generated/**
          db.php
